[package]
name = "suppaftp"
version = "4.1.0"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>", "Christian Visintin <christian.visintin1997@gmail.com>"]
documentation = "https://docs.rs/suppaftp/"
repository = "https://github.com/veeso/rust-suppaftp"
description = "A super FTP/FTPS client library for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["ftp", "ftps", "network-protocol", "async"]
categories = ["asynchronous", "network-programming"]

[lib]
name = "suppaftp"
path = "src/lib.rs"

[features]
# Enable support of FTPS which requires native-tls (openssl is required on Linux)
secure = ["native-tls"]

# Must be enabled whenever testing with docker containers
with-containers = []

# Add debug output (to STDOUT) of commands sent to the server
# and lines read from the server
debug_print = []

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"
native-tls = { version = "^0.2", optional = true }
regex = "1.4.2"
thiserror = "1.0.26"

[dev-dependencies]
pretty_assertions = "0.7.2"
rand = "0.8.4"
