[package]
name = "ftp4"
version = "4.1.0"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>", "Christian Visintin <christian.visintin1997@gmail.com>"]
documentation = "https://docs.rs/ftp4/"
repository = "https://github.com/veeso/rust-ftp4"
description = "FTP/FTPS client library for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["ftp"]
categories = ["network-programming"]

[lib]
name = "ftp4"
path = "src/lib.rs"

[features]
# Enable support of FTPS which requires native-tls (openssl is required on Linux)
secure = ["native-tls"]

# Must be enabled whenever testing with docker containers
with-containers = []

# Add debug output (to STDOUT) of commands sent to the server
# and lines read from the server
debug_print = []

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"
native-tls = { version = "^0.2", optional = true }
regex = "1.4.2"
thiserror = "1.0.26"

[dev-dependencies]
pretty_assertions = "0.7.2"
